### ISSUE TITLE
Spark WebUI is not responding

### ISSUE THREAD

**Issue by marianormuro** [Segence/docker-hadoop#1]
The spark UI is not running after following the instructions for setting up a local hadoop cluster (not stand alone). All other UIs are up, HDFS is running.

**Comment by robvadai** [comment]
Hi @marianormuro,

Spark is using YARN in this set up which means that a standalone Spark server is not automatically started.
If you start a Spark job, either through submitting a JAR file to YARN or opening a Spark Shell session (as described under the [Running a sample interactive Spark job](https://github.com/Segence/docker-hadoop/blob/master/README.md#running-a-sample-interactive-spark-job) section in the README) you should be able to get to the Spark UI on this URL: http://localhost:4040/jobs/

Please let me know how it goes.
